apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-app
  labels:
    app: {{ .Release.Name }}-todo-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-todo-app
    spec:
      containers:
          - name: todo-app
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
              - containerPort: {{ .Values.service.targetPort }}
            env:
              - name: SPRING_DATASOURCE_URL
                value: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
              - name: SPRING_DATASOURCE_USERNAME
                value: "{{ .Values.database.username }}"
              - name: SPRING_DATASOURCE_PASSWORD
                value: "{{ .Values.database.password }}"
              - name: SPRING_JPA_HIBERNATE_DDL_AUTO
                value: "{{ .Values.env.SPRING_JPA_HIBERNATE_DDL_AUTO }}"
            readinessProbe:
              tcpSocket:
                port: {{ .Values.service.targetPort }}
              initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
              failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            livenessProbe:
              tcpSocket:
                port: {{ .Values.service.targetPort }}
              initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
              failureThreshold: {{ .Values.livenessProbe.failureThreshold }}