apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-argocd
  namespace: default
  labels:
    app: todo-app-argocd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: todo-app-argocd
  template:
    metadata:
      labels:
        app: todo-app-argocd
    spec:
      containers:
        - name: todo-app-argocd
          image: nginx:1.25
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"