sonar.projectKey=AndriiLupoi_Dev-ops_basic-springBoot-project-to-Docker
sonar.organization=andriilupoi

sonar.projectName=My Java SpringBoot Project
sonar.projectVersion=1.0

# Шлях до вихідного коду
sonar.sources=src/main/java
sonar.tests=src/test/java

# Кодування
sonar.sourceEncoding=UTF-8

# Покриття (JaCoCo)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
